import 'styles/globals.scss';
import { Inter } from 'next/font/google';
import GoogleTagManager from '@/components/GoogleTagManager';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <GoogleTagManager id={process.env.GTM_CONTAINER_ID || 'GTM-xxxxxxx'} />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
